version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      RUN_SEED: "false"
      DATABASE_URL: ${DATABASE_URL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DISABLE_AUTH: "false"
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      CORS_ORIGIN: ${CORS_ORIGIN}
      APP_URL: ${APP_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      POSAPI_BASE_URL: ${POSAPI_BASE_URL}
      POSAPI_MERCHANT_TIN: "37900846788"
      POSAPI_POS_NO: "10013198"
      POSAPI_BRANCH_NO: "001"
      POSAPI_DISTRICT_CODE: "2501"
    ports:
      - "8083:8080"
    networks:
      - mdent-dev-net
    restart: unless-stopped
    volumes:
      - media_data_dev:/data/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_PORTAL_URL: ${NEXT_PUBLIC_PORTAL_URL}
    ports:
      - "3001:3000"
    networks:
      - mdent-dev-net
    restart: unless-stopped

networks:
  mdent-dev-net: {}

volumes:
  media_data_dev:
